### ISSUE TITLE
Rename project to GDP

### ISSUE THREAD

**Issue by BoPeng** [vatlab/vat-dp#7]
vat-dp is sort of long and it would be difficult to publish it as a standalone product. Would it be better to rename the project to `Genomic Data Provider` (GDP) or something in line with `Universal Genomic Data Exchange Protocol`?

**Comment by BoPeng** [comment]
I think the value of this project should be a web protocol, and an API to perform data analysis (e.g. R or Python API). The API would be general enough to accommodate other data types and other implementation of the API.

**Comment by gaow** [comment]
I very much agree. The association part of the VAT software is hard to keep up to date and `rvtest` (Bioinformatics, 2015 / 2016) now provides a more comprehensive set of analysis. With proper data protocol and a demonstration of how it works with a few association tools in different context (GWAS, exome rare variants, eQTL discovery, pathway analysis, CNV, etc) we should be doing a much better job than focusing on extending VAT.

GDP is not a very Google friendly name. GDEP does not have very meaning search results as of now :)

**Comment by BoPeng** [comment]
At least GDP is easy to remember, as easy as sos. :-)

Dr. Leal's lab is responsible for the association part of VAT and I cannot really help if she does not allocate enough resources to it. I suppose it would be relatively easy to catch up if we provide a good data model and wrapper for third-party tools (even `rvtest`).

**Comment by gaow** [comment]
If we provide a good data model I'd like to explore wrappers for eQTL and CNV association analysis.
